<?php

namespace AppBundle\Repository;

/**
 * ListappRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListappRepository extends \Doctrine\ORM\EntityRepository
{
}
